# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0002_gene'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='name',
        ),
        migrations.AddField(
            model_name='gene',
            name='gene',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gene',
            name='locus_tag',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gene',
            name='product',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
