# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0003_auto_20170720_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenomicIsland',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=10)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genomes.Genome')),
            ],
        ),
    ]
