# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20170718_1718'),
        ('genomes', '0004_genomicisland'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenomicIslandCluster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Analysis')),
                ('genomic_islands', models.ManyToManyField(to='genomes.GenomicIsland')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='genomicislandcluster',
            unique_together=set([('number', 'analysis')]),
        ),
    ]
