# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analysis_clusters'),
        ('genomes', '0004_genomicisland'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGenomicIsland',
            fields=[
                ('genomicisland_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='genomes.GenomicIsland')),
                ('color', models.CharField(max_length=30)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Analysis')),
            ],
            bases=('genomes.genomicisland',),
        ),
    ]
