# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 06:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genomes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(max_length=765, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('submit_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_time', models.DateTimeField(null=True)),
                ('complete_time', models.DateTimeField(null=True)),
                ('genomes', models.ManyToManyField(to='genomes.Genome')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(max_length=765, unique=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('complete_time', models.DateTimeField(null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='analysiscomponent',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.AnalysisType'),
        ),
        migrations.AlterUniqueTogether(
            name='analysiscomponent',
            unique_together=set([('type', 'analysis')]),
        ),
        migrations.AlterUniqueTogether(
            name='analysis',
            unique_together=set([('name', 'owner')]),
        ),
    ]
