# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-18 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='celery_task_id',
            field=models.CharField(max_length=765),
        ),
        migrations.AlterField(
            model_name='analysiscomponent',
            name='celery_task_id',
            field=models.CharField(max_length=765),
        ),
    ]
