# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20170718_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='clusters',
            field=models.TextField(blank=True),
        ),
    ]
