image: python:3.6

stages:
  - test
  - pages

before_script:
  - pip install -r Chef/cookbooks/baseconfig/files/requirements.txt
  - cd IslandCompare
  - python manage.py makemigrations
  - python manage.py migrate

test:
  stage: test
  script:
    - coverage run --source='.' manage.py test
    - coverage html
    - coverage report
  artifacts:
    paths:
      - htmlcov/
