language: python
python:
  - "3.6"
install:
  - "pip install celery==4.0.2"
  - "pip install Django==1.10.4"
  - "pip install django-celery-results==1.0.1"
  - "pip install djangorestframework==3.5.3"
  - "pip install drfdocs==0.0.11"
before_script:
  - "python IslandCompare/manage.py makemigrations"
  - "python IslandCompare/manage.py migrate"
script:
  - "python IslandCompare/manage.py test IslandCompare"
