language: python
python:
  - "2.7"
install:
  - "pip install Django==1.9"
script:
  - "python IslandCompare/manage.py makemigrations"
  - "python IslandCompare/manage.py migrate"
  - "python IslandCompare/manage.py test"
