language: python
python:
  - "3.6"
install:
  - "pip install celery==4.0.2"
  - "pip install Django==1.10.4"
  - "pip install django-celery-results==1.0.1"
  - "pip install djangorestframework==3.5.3"
  - "pip install drfdocs==0.0.11"
  - "pip install numpy==1.12.0"
  - "pip install biopython==1.68"
  - "mkdir apps"
  - "tar xzvf Chef/cookbooks/baseconfig/files/parsnp-Linux64-v1.2.tar.gz -C apps"
  - "tar xzvf Chef/cookbooks/baseconfig/files/mauve_linux_snapshot_2015-02-13.tar.gz -C apps"
before_script:
  - "python IslandCompare/manage.py makemigrations"
  - "python IslandCompare/manage.py migrate"
  - "mkdir temp"
  - "mkdir temp/parsnp"
  - "mkdir temp/mauve"
script:
  - "python IslandCompare/manage.py test IslandCompare"
  - "python IslandCompare/manage.py test IslandCompare --pattern=\"integration_tests*.py\""