version: '3'
services:
    proxy:
        image: nginx:latest
        container_name: proxy
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./proxy.log:/etc/nginx/error_log.log
        ports:
            - 80:80
            - 443:443
    galaxy:
        build: .
        container_name: Galaxy
        privileged: true
        expose:
            - "80"
        volumes:
            - ./galaxy-export:/export/
        environment:
            GALAXY_CONFIG_MASTER_API_KEY: '83D5jaba7330aDAAkakjGa247'
            GALAXY_CONFIG_BRAND: 'IslandCompare Dev Test'
            GALAXY_CONFIG_TOOL_CONFIG_FILE: 'config/tool_conf.xml.sample,config/shed_tool_conf.xml.sample,/home/galaxy/local_tools/tool_conf.xml'
            GALAXY_CONFIG_WATCH_TOOLS: 'true'
            GALAXY_CONFIG_CONDA_AUTO_INSTALL: 'true'
