version: '3'
services:
    proxy:
        image: nginx:latest
        container_name: proxy
        volumes:
            - ${PWD}/docker/nginx.conf:/etc/nginx/nginx.conf
            - ${PWD}/docker/proxy.log:/etc/nginx/error_log.log
        ports:
            - 80:80
            - 443:443
    galaxy:
        build:
            context: .
            dockerfile: docker/Galaxy.docker
        container_name: Galaxy
        expose:
            - "80"
        volumes:
            - ./docker/galaxy-export:/export/
#       environment:
#           GALAXY_CONFIG_MASTER_API_KEY: '83D5jaba7330aDAAkakjGa247'
#           GALAXY_CONFIG_BRAND: 'IslandCompare Dev Test'
#           GALAXY_CONFIG_TOOL_CONFIG_FILE: 'config/tool_conf.xml.sample,config/shed_tool_conf.xml.sample,/home/galaxy/local_tools/tool_conf.xml'
#           GALAXY_CONFIG_WATCH_TOOLS: 'true'
#           GALAXY_CONFIG_CONDA_AUTO_INSTALL: 'true'
#           GALAXY_CONFIG_LOG_LEVEL: 'DEBUG'
#           GALAXY_CONFIG_USE_REMOTE_USER: 'true'
#           GALAXY_CONFIG_REMOTE_USER_SECRET: 'VxhVQ8e4qddE773BZBxcMxzYhUTcY4Ye'
#           GALAXY_CONFIG_REMOTE_USER_MAILDOMAIN: 'sfu.ca'
#           GALAXY_CONFIG_ADMIN_USERS: 'TLaQWx6F9B5tPuAdLMBz4scTwqTTY3hhGa4jTK3AQf7bTzPTM4GfLdHDDfgtRjf4'
#TODO       GALAXY_CONFIG_REMOTE_USER_LOGOUT_HREF: 
    web:
        image: node:alpine
        container_name: web
        working_dir: /home/node/app
        environment:
            - NODE_ENV=dev
        volumes:
            - ./ui/:/home/node/app
        expose:
            - "8080"
        command: "./startup"
