name: Node CI

on:
  push:
    branches: 
      - galaxy
    paths:
      - ui/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build
      working-directory: ui/
      run: |
        npm ci
        npm run build --if-present
        #npm test
      env:
        CI: true
