name: Autobuild

on:
  push:
    branches: 
      - galaxy
    paths:
      - ui/**
      - .github/workflows/nodejs.yml


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build
      working-directory: ui/
      run: |
        npm ci
        npm run build --if-present
      env:
        CI: true
    #- name: Archive production artifacts
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: dist
    #    path: ui/dist
    - name: deploy-via-scp
      uses: horochx/deploy-via-scp@v1.0.1
      with:
        local: ui/dist/*
        remote: /srv/ui/
        host: admin.pathogenomics.sfu.ca
        port: 22
        user: ${{ secrets.AWS_IC_USER }}
        key: ${{ secrets.AWS_IC_KEY }}
